global:
  scrape_interval: 15s # Cada cuánto tiempo pedirá datos

scrape_configs:
  - job_name: 'django-backend'
    static_configs:
      - targets: ['backend:8000'] # Apunta al nombre del servicio en docker-compose